<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Linear_Transformation_Coding_Act_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Given Equations:**

4x +10y+8z = 44

10x+26y+26z = 128

8x+26y+61z = 214

In [7]:
import numpy as np

mA = np.array([[4,10,8],[10,26,26],[8,26,61]]) #creation of matrix A
print("Matrix A")
print(mA)

inv_mA = np.linalg.inv(mA) #inversed matrix A
print("INVERSED Matrix A")
print(inv_mA)

Matrix A
[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
INVERSED Matrix A
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [11]:
mB = np.array([[44],[128],[214]]) #creation of matrix B
print("Matrix B")
print(mB)

Matrix B
[[ 44]
 [128]
 [214]]


In [12]:
dotAB = np.dot(inv_mA,mB) #dot product of inversed matrix A and matrix B
print("DOT product of inversed matrix A and matrix B")
print(dotAB)

DOT product of inversed matrix A and matrix B
[[-8.]
 [ 6.]
 [ 2.]]


*To check if the answer is correct*

In [14]:
check1 = np.dot(mA,dotAB) #dot product of matrix A and dotproduct of matrices A & B , product must be the same with matrix B
print(check1)

[[ 44.]
 [128.]
 [214.]]
