<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [49]:
import numpy as np 

Matrix1 = np.full((5,5),2) #using numpy full function with a 5x5 length and width, full of number 2
print(Matrix1)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


##Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [16]:
Matrix2 = np.triu([[1,2,3],[4,5,6],[7,8,9]]) #using the numpy function 'triu' meaning upper triangular
print(Matrix2)

#another way
Matrix2_1 = np.array([[1,2,3],[0,5,6],[0,0,9]]) #manually inputting the zeroes in the matrix
print("\n")
print(Matrix2_1)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


[[1 2 3]
 [0 5 6]
 [0 0 9]]


##Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [50]:
Matrix3 = np.full((3,3),1) #using the numpy full function with 3x3 length and width making it symmetrical square matrix
print(Matrix3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


##Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [28]:
Matrix4C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print("Matrix C")
print(Matrix4C)

inverseC = np.linalg.inv(Matrix4C)
print("\nInversed Matrix C")
print(inverseC)

Matrix C
[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Inversed Matrix C
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [53]:
print("Matrix C") #displaying matrix C from the previous cell
print(Matrix4C) 

print("\nDeterminant of Matrix C") #displaying the determinant of matrix
print("|C| =",round(np.linalg.det(Matrix4C))) #using the numpt function to get the determinant

Matrix C
[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Determinant of Matrix C
|C| = 5


##Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [55]:
Matrix6 = np.array([[5,4,1],[10,9,4],[10,13,15]]) #the matrix based on the given linear equations
print("Given Matrix A")
print(Matrix6)

inverse6 = np.linalg.inv(Matrix6) #inverting matrix A
print("\nInversed Matrix A")
print(inverse6)

MConstant = np.array([[3.4],[8.8],[19.2]]) #matrix B based on he given linear equations
print("\nMatrix B")
print(MConstant)

print("\n**To get the value or roots of the equation, proceed using Dot Product to Inversed Matrix A and Matrix B**") 

dotAB = np.dot(inverse6,MConstant) #dot product of inversed matrix A and matrix B
print("\nDOT product of Inversed Matrix A and Matrix B")
print(dotAB)

print("\n**For checking if correct, proceed using Dot product to the solved dot product and Matrix A. The answer must be the same to Matrix B**")

dotAB = np.dot(Matrix6,dotAB) #dot product of inversed matrix A and matrix B
print(dotAB)





Given Matrix A
[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

Inversed Matrix A
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]

Matrix B
[[ 3.4]
 [ 8.8]
 [19.2]]

**To get the value or roots of the equation, proceed using Dot Product to Inversed Matrix A and Matrix B**

DOT product of Inversed Matrix A and Matrix B
[[0.2]
 [0.4]
 [0.8]]

**For checking if correct, proceed using Dot product to the solved dot product and Matrix A. The answer must be the same to Matrix B**
[[ 3.4]
 [ 8.8]
 [19.2]]
