<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Vectors_DEMO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Algebra

In [ ]:
#numpy
import numpy as np
a = np.array([1,2,3]) #this is an example of 1x3 matrix
print(a)

[1 2 3]


In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #2x3 matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3x3 matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#numpy
import numpy as np
d1 = np.full((3,3),7)
print(d1)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
e1 = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [ ]:
import numpy as np
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
g = np.zeros((2,2))
print(g)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
h = np.empty((0,12))
print(h)

[]
