<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Application_of_Systems_of_Linear_Equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**EXAMPLE 1**

#The Price of One Apple and One Orange

20x + 10y = 350

17x + 22y = 500

In [14]:
import numpy as np

A = np.array([[20,10],[17,22]])
print("Matrix A")
print(A)

B = np.array([[350],[500]])
print("Matrix B")
print(B)

invA = np.linalg.inv(A)
print("Inversed Matrix A")
print(invA)

answer = np.linalg.inv(A).dot(B) #method 1
print("Dot product")
print(answer)

answer1 = np.dot(invA,B) #method 2
print("Dot product")
print(answer1)

Matrix A
[[20 10]
 [17 22]]
Matrix B
[[350]
 [500]]
Inversed Matrix A
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
Dot product
[[10.]
 [15.]]
Dot product
[[10.]
 [15.]]


##**Another Way of Solving**

In [16]:
A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)

X = np.linalg.solve(A,B) #solving for X and Y using numpy function
print(X)

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


##*Scipy*

In [17]:
import numpy as np
from scipy.linalg import solve

A = np.array([[20,10],[17,22]])
B = np.array([[350],[500]])
print(A)
print(B)

X = solve(A,B) #solving for X and Y using scipy function
print(X)

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


##**EXAMPLE 2**

##Solving for 3 Linear Equations with Unknown Variables of X, Y, and Z

4x + 3y + 2z = 25

-2x + 2y + 3z = -10

3x  - 5y + 2z = -4

In [24]:
ma = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
mb = np.array([[25],[-10],[-4]])
print(A)
print(B)

x1 = solve(ma,mb) #solving for X and Y using scipy function
print(x1)

[[20 10]
 [17 22]]
[[ 25]
 [-10]
 [ -4]]
[[ 5.]
 [ 3.]
 [-2.]]
