<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRELIM EXAM
Vince Kazer M. Villasor (58019)

# Question #1
Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [37]:
import numpy as np
matrixC = np.array([[1,2,3,4],[5,1,7,8],[9,10,1,12],[13,14,15,1]]) #4x4 matrix with diagonal elements of one
C1 = np.diagonal([[1,2,3,4],[5,1,7,8],[9,10,1,12],[13,14,15,1]]) #used to show the diagonal elements in matrix C

#displaying the matrix' name
print("Matrix C") #the matrix' name
print(matrixC)

#displaying the diagonal elements
print("\n---------")
print("Diagonal Elements")
print(C1)

Matrix C
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10  1 12]
 [13 14 15  1]]

---------
Diagonal Elements
[1 1 1 1]


# Question #2
In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [36]:
import numpy as np
matrixC= np.array([[1,2,3,4],[5,1,7,8],[9,10,1,12],[13,14,15,1]]) #4x4 matrix with diagonal elements of one
Prod = 2*C #this the a scaling process

#displaying the matrix' name
print("Matrix C") 
print(matrixC)

#displaying the product
print("\n---------")
print("Doubled value of Matrix C")
print("(2 * Matrix C)\n")

print(Prod)
#it will turn all the diagonal elements into two


Matrix C
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10  1 12]
 [13 14 15  1]]

---------
Doubled value of Matrix C
(2 * Matrix C)

[[ 2  4  6  8]
 [10  2 14 16]
 [18 20  2 24]
 [26 28 30  2]]


# Question #3
Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [30]:
import numpy as np
mA = np.array([2,7,4]) #matrix A
mB = np.array([3,9,8]) #matrix A
crossprod = np.cross(mA,mB) #computing the cross product

#displaying the matrices
print("Matrix A") 
print(mA)
print("\nMatrix B")
print(mB)

#displaying the product
print("\n---------")
print("Cross Product")
print(crossprod)


Matrix A
[2 7 4]

Matrix B
[3 9 8]

---------
Cross Product
[20 -4 -3]
