<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)_Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Representing Vectors

In [5]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print("Vector A is ", A)
print("Vector B is ", B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


## Describing Vectors in NumPy

In [11]:
### checking shapes
### shapes tell us

import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape #rows and column will be the output
pool.ndim # dimension will be the output


2

In [18]:
U = np.array([[1,2,3],[4,5,6]])
print(U)
U.shape
U.ndim
U.size

[[1 2 3]
 [4 5 6]]


6

#### Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations.

###Addition of Vectors

In [20]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
print(sum)

[1 1 0]


In [25]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

###Subtraction of Vectors

In [31]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
diff = addend1 - addend2
diff

array([-1, -1,  0])

In [30]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
diff = np.subtract(addend1,addend2)
diff

array([-1, -1,  0])

###Scaling

In [32]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

## Cross Product

In [36]:
A = np.array([2,3])
B = np.array([1,7])

#compute the cross product of A and b
cross = np.cross(A,B)
print(cross)

11


In [ ]:
          #   + - +
A = np.array([2,3,4])
B = np.array([1,7,1])

#compute the cross product of A and b
cross = np.cross(A,B)
print(cross)

###Dot Product??

In [39]:
A = np.array([2,3])
B = np.array([1,7])

#compute the dot product of A and b
dot1 = np.dot(A,B)
print(dot1)

23
