<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###EXAMPLE 1

In [38]:
#should not be use for eigenvalue and eigenvectors. 
#THIS IS FOR LINEAR TRANSFORMATION

import numpy as np

matrix_A = np.array([[-12,3],[4,1]])
print("Matrix A")
print(matrix_A)

matrix_B = np.array([[0],[0]])
print("\n Matrix B / Constant")
print(matrix_B)

invA = np.linalg.inv(matrix_A)
print("\n Inverse A")
print(invA)

#another method
prod = np.dot(invA,matrix_B)
print("\n Dot Product")
print(prod)

#using scipy
#from scipy.linalg import solve
#prod2 = solve(matrix_A,matrix_B)
#print("\n Dot Product")
#print(prod2)




Matrix A
[[-12   3]
 [  4   1]]

 Matrix B / Constant
[[0]
 [0]]

 Inverse A
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]

 Dot Product
[[0.]
 [0.]]


In [43]:
#using eigen AND for eigenvalues and eigenvectors
import numpy as np
from numpy.linalg import eig

A = np.array([[-6,3],[4,5]])
print(A)

w,v = np.linalg.eig(A)
print("\nThe Eigenvalues is/are:", w)
print("\nThe right Eigenvectors are:\n", v)
print("\n Rounded Vector")
roun1 = v.round()
print(roun1)


[[-6  3]
 [ 4  5]]

The Eigenvalues is/are: [-7.  6.]

The right Eigenvectors are:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]

 Rounded Vector
[[-1. -0.]
 [ 0. -1.]]


###EXAMPLE 2

In [60]:
import numpy as np
from numpy.linalg import eig

A = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)

s,t = np.linalg.eig(A)
print("\nThe Eigenvalues is/are:", s.round())
print("The right Eigenvectors are:\n", t.round())


c = np.dot(A,t.round())
print("\nsupposed answers??")
print(c)

[[2 2 4]
 [1 3 5]
 [2 3 4]]

The Eigenvalues is/are: [ 9.  1. -1.]
The right Eigenvectors are:
 [[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

supposed answers??
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]


In [61]:
#for checking?

f = np.array([[-1],[-1],[-1]])
print(f)

g = np.dot(A,f)
print("\n")
print(g)

[[-1]
 [-1]
 [-1]]


[[-8]
 [-9]
 [-9]]
