<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Program to Inverse

In [26]:
import numpy as np

A = np.array([[1,2],[4,7]])
print(A)
invA = (np.linalg.inv(A))
print("\n", invA)


[[1 2]
 [4 7]]

 [[-7.  2.]
 [ 4. -1.]]


In [27]:
C = np.dot(A, invA)
print(C)

[[1. 0.]
 [0. 1.]]


## Python Program to Inverse a 3x3 Matrix

##### A = [6,1,1], [4,-2,5], [2,8,7]

In [42]:
## Python Program to transpose a 3x3 Matrix

mA = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(mA)
alter_mA = np.transpose(mA) #changes row to column
print("\n")
print(alter_mA)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [49]:
## Python Program to inverse a 3x3 Matrix

mA = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(mA)
inv_mA = (np.linalg.inv(mA)) #matrix B
print("\n")
print(inv_mA)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


## Program Code Product of mA and mB

In [48]:
productAB = np.dot(mA,inv_mA)
print(productAB)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


## Coding Activity 3
##### Create a Python Program to inverse and transpose a 4x4 matrix,
###### A = [6,1,1,3], [4,-2,5,1], [2,8,7,6], [3,1,9,7]

In [60]:
#Python Program to Inverse the given Matrix

A = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]]) #the given matrix

print("Matrix A") #label for the given matrix
print(A)
print("\n")

B = np.linalg.inv(A) #used to inverse the matrix
print("Inversed Matrix A") #label for the inversed matrix, this is technically matrix B
print(B)



Matrix A
[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]


Inversed Matrix A
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


In [76]:
#Program Code of Product of the Matrix A and inversed Matrix A

productAB = np.dot(A, B) #used to get the dot product of the two matrices 
print("Product of Matrix A and inversed Matrix A") #label
print(productAB)

print("\n")
print("Diagonal Elements of the Product") #label
C = np.diagonal(productAB) #used to show the elements in the diagonal position
print(C)

Product of Matrix A and inversed Matrix A
[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17  5.55111512e-17]
 [-1.24900090e-16  1.00000000e+00 -5.55111512e-17 -2.77555756e-17]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [-1.52655666e-16 -2.22044605e-16 -8.32667268e-17  1.00000000e+00]]


Diagonal Elements of the Product
[1. 1. 1. 1.]


In [77]:
## Python Program to transpose the given matrix

A = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]]) #given matrix
print("Matrix A") #label for the given matrix
print(A)

print("\n")
alter_A = np.transpose(A) #used to turn the row or column into column or row, respectively.
print("Transposed Matrix A") #label for the transposed matrix
print(alter_A)

Matrix A
[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]


Transposed Matrix A
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
