<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#solving for the determinant of the given matrix

import numpy as np #numerical python 
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]]) #the given array

print("Matrix A") #displaying the matrix
print(A)
print("\n")
print("Determinant of Matrix A") #displaying the determinant of matrix
print("|A| =",round(np.linalg.det(A)))

Matrix A
[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


Determinant of Matrix A
|A| = -14
