<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### To find the inverse of a matrix, the matrix is passed to to the linalg.in() of the NumPy module

##**EXAMPLE OF SOLVING 2 LINEAR EQUATIONS**

In [4]:
import numpy as np

A = np.array([[4,3],[-5,9]]) #creation of matrix A
print(A)

inv_A = np.linalg.inv(A) #creation of inversed matrix A
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [7]:
B = np.array([[20],[26]]) #creation of matrix b
print(B)

[[20]
 [26]]


In [9]:
X = np.linalg.inv(A).dot(B) #dot product of inversed matrix A and matrix B
print(X)

[[2.]
 [4.]]


In [10]:
#another method to solve for dot product 
X =np.dot(inv_A,B) 
print(X)

[[2.]
 [4.]]


##**EXAMPLE OF SOLVING 3 LINEAR EQUATIONS**


In [26]:
A1 = np.array([[4,3,2],[-2,9,3],[3,-5,2]]) #creation of matrix A1
print("Matrix A1")
print(A1)

inv_A1 = np.linalg.inv(A1) #inversed matrix A1
print("INVERSED Matrix A1")
print(inv_A1)

Matrix A1
[[ 4  3  2]
 [-2  9  3]
 [ 3 -5  2]]
INVERSED Matrix A1
[[ 0.24087591 -0.11678832 -0.06569343]
 [ 0.09489051  0.01459854 -0.11678832]
 [-0.12408759  0.21167883  0.30656934]]


In [27]:
B1 = np.array([[25],[-10],[-4]]) #creation of matrix B
print("Matrix B1")
print(B1)

Matrix B1
[[ 25]
 [-10]
 [ -4]]


In [29]:
X1 = np.dot(inv_A1,B1) #dot product of inversed matrix A1 and matrix B1 
print("DOT product of inversed matrix A1 and B1")
print(X1)

DOT product of inversed matrix A1 and B1
[[ 7.45255474]
 [ 2.69343066]
 [-6.44525547]]


*To check if the answer is correct*

In [25]:
check = np.dot(A1,X1)
print(check) #must be the same as matrix B1

[[ 25.]
 [-10.]
 [ -4.]]


##**APPLICATION / WORD PROBLEM**


In [19]:
givenA = np.array([[20,10],[17,22]]) #creation of matrix A
print(givenA)

i_givenA = np.linalg.inv(givenA) #inversed of matrix A
print(i_givenA)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [20]:
constantB = np.array([[350],[500]]) #creation of matrix B
print(constantB)

[[350]
 [500]]


In [21]:
dotX = np.dot(i_givenA,constantB) #dot product of inversed matrix A and matrix B
print(dotX)

[[10.]
 [15.]]


*To check if the answer is correct*

In [24]:
B = np.dot(givenA,dotX)
print(B)

[[350.]
 [500.]]
