<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam


VINCE KAZER M. VILLASOR

**Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)**

In [90]:
print("A + B + C = 89")
print("A = C - 6")
print("B = 3C")

print("\nSubstitute A and B to the first equation")
print("C-6 + 3C + C = 89")
print("\nThen solve")
print("5C = 95")

print("\nC = 19")
C = 19
print("A =", C - 6)
print("B =", 3*C)

A + B + C = 89
A = C - 6
B = 3C

Substitute A and B to the first equation
C-6 + 3C + C = 89

Then solve
5C = 95

C = 19
A = 13
B = 57


**Problem 2. Solve each system: (30 points)**

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [84]:
#solving the equation using scipy function

import numpy as np
from scipy.linalg import solve

A2 = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print("The given matrix A")
print(A2)

B2 = np.array([[5],[15],[-20]])
print("\nThe given matrix on the right side of the equation")
print(B2)

#X = solve(A2,B2)
#print(X)

print("\nNote: The given matrix have is inconsistent that resulted to a SINGULAR MATRIX meaning the determinant is equal to ZERO or simply has no determinant \n where INVERSE MATRIX for the given is not possible hence making the linear equation unsolvable")



The given matrix A
[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

The given matrix on the right side of the equation
[[  5]
 [ 15]
 [-20]]

Note: The given matrix have is inconsistent that resulted to a SINGULAR MATRIX meaning the determinant is equal to ZERO or simply has no determinant 
 where INVERSE MATRIX for the given is not possible hence making the linear equation unsolvable


**Problem 3. 
Find the eigenvalue/s
Find the eigenvectors**

In [91]:
#using eigen from numpy to find for the eigenvalues and eigenvectors of the given matrix

import numpy as np
from numpy.linalg import eig

mA = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print("Matrix A")
print(mA)

w,v = np.linalg.eig(mA)
print("\nThe Eigenvalues are:", w.round())
print("\nTHe Eigenvectors are:\n", v.round())

b = np.dot(mA,v.round())
print("\nAnswers")
print(b)

#for checking?
print("\nFrom one column of Eigenvectors")
c = np.array([[0],[-1],[-0]]) #change the value depending on the Eigenvectors the user want to check
print(c)

d = np.dot(mA, c)
print("\nThe answer should be the same to the same column of the Answers")
print(d)


Matrix A
[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The Eigenvalues are: [-1.  3.  2.]

THe Eigenvectors are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]

Answers
[[-5. -3.  2.]
 [ 9.  3.  0.]
 [ 3.  0.  2.]]

From one column of Eigenvectors
[[ 0]
 [-1]
 [ 0]]

The answer should be the same to the same column of the Answers
[[-5]
 [ 9]
 [ 3]]
