<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/(LA)%20Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical Lab Exam 1

Vince Kazer M. Villasor
58019

# Problem 1

In [47]:
#creating matrix

import numpy as np

A = np.array([[1,2,3],[4,5,6]]) #matrix A
print("Matrix A")
print(A)

B = np.array([[1,2],[3,4],[5,6]]) #matrix B
print("\nMatrix B")
print(B)

C = np.array([[1,2,3],[4,5,6],[7,8,9]]) #matrix C
print("\nMatrix C")
print(C)

D = np.array([[1,2],[3,4]]) #matrix D
print("\nMatrix D")
print(D)

B1 = np.array([[1,2],[3,4],[5,6]]).reshape(2,3)
print("\nRESHAPED Matrix B")
print(B1)

print("\n---------")
print("a. MULTIPLICATION (mA*reshapedmB)") #the original matrix B is cannot be used 
print(A*B1)                                #to multiply with matrix A because they do not have the same shape

print("\n---------")
print("b. ADDITION (mD+mD)")
sum = np.add(D,D)
print(sum)

print("\n---------")
print("c. MULTIPLICATION (2*C)")
print(2*C)

Matrix A
[[1 2 3]
 [4 5 6]]

Matrix B
[[1 2]
 [3 4]
 [5 6]]

Matrix C
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix D
[[1 2]
 [3 4]]

RESHAPED Matrix B
[[1 2 3]
 [4 5 6]]

---------
a. MULTIPLICATION (mA*reshapedmB)
[[ 1  4  9]
 [16 25 36]]

---------
b. ADDITION (mD+mD)
[[2 4]
 [6 8]]

---------
c. MULTIPLICATION (2*C)
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Problem 2

In [49]:
# 0 = 5x + 3y - z (the linear combination)

import numpy as np

print("The Matrix based on the given equation, 0 = 5x + 3y - z:\n")
equation = np.array([5,3,-1])
print(equation)


print("\n---------")
print("SHAPE") #i also tested different 1x3 matrix and it always show (3,) as the output for shape
print(equation.shape)
print("(1,3)")

print("\n---------")
print("DIMENSION")
print(equation.ndim)

print("\n---------")
print("SIZE")
print(equation.size)

print("\n---------")
print("DATA TYPE")
print(equation.dtype)

print("\n---------")
print("TYPE of MATRIX")
print("Row Matrix")

The Matrix based on the given equation, 0 = 5x + 3y - z:

[ 5  3 -1]

---------
SHAPE
(3,)
(1,3)

---------
DIMENSION
1

---------
SIZE
3

---------
DATA TYPE
int64

---------
TYPE of MATRIX
Row Matrix
