<a href="https://colab.research.google.com/github/vincev16/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix and Its Operation

In [19]:
#numpy
import numpy as ex1


A = ex1.array([[-5,0],[4,1]])
print("matrix A")
print(a)

B = ex1.array([[6,-3],[2,3]])
print("\nmatrix B")
print(B)

print("\n---------")
print("ADDITION (mA+mB)")
print(A+B)

print("\n---------")
print("SUBTRACTION1(mB-mA)")
print(B-A)

print("\n---------")
print("SUBTRACTION2(mA-mB)")
print(A-B)

matrix A
[[-5  0]
 [ 4  1]]

matrix B
[[ 6 -3]
 [ 2  3]]

---------
ADDITION (mA+mB)
[[ 1 -3]
 [ 6  4]]

---------
SUBTRACTION1(mB-mA)
[[11 -3]
 [-2  2]]

---------
SUBTRACTION2(mA-mB)
[[-11   3]
 [  2  -2]]
